import { useState } from 'react'
import {
  Accordion,
  AccordionSummary,
  AccordionDetails,
  Typography,
  Box,
} from '@mui/material'
import ExpandMoreIcon from '@mui/icons-material/ExpandMore'

const StudyOutline = () => {
  const [expanded, setExpanded] = useState<boolean>(true)

  const handleOnClick = () => {
    setExpanded((prev) => !prev)
  }

  return (
    <Accordion
      expanded={expanded}
      sx={{
        borderBottom: '0px solid white',
        boxShadow: 'none',
      }}
    >
      <AccordionSummary
        onClick={handleOnClick}
        expandIcon={<ExpandMoreIcon />}
        aria-controls="panel1a-content"
        id="panel1a-header"
        sx={{
          '& .MuiAccordionSummary-expandIconWrapper.Mui-expanded': {
            transform: 'rotate(90deg)',
          },
        }}
      >
        <Typography variant="h4">Study Outline</Typography>
      </AccordionSummary>
      <AccordionDetails
        sx={{
          display: 'flex',
          flexDirection: 'column',
          rowGap: '1.5rem',
          borderTop: '1px solid rgba(0, 0, 0, .125)',
        }}
      >
        <SubSection
          title={'The Study'}
          body={[
            'A common method of assessment in Computer Science courses involves asking students to write and submit code to solve a particular problem. A well-known phenomenon is that students are able to produce code that meets the requirements but do not fully understand it. It is thought to be useful to have the students reflect on the code that they have written by asking them questions about their code.',
            'However, manually generating and marking these questions about each individual student’s code is infeasible. Therefore, we have developed a system that automatically generates questions about a student’s code.',
            'The questions generated by this system are what we are calling “Questions about Learner’s Code” (QLCs).',
            'We have developed this tool, which is a web application that has been developed using standard web technologies, that automatically generates QLCs about a student’s submitted Python code. We aim to test the effectiveness of this tool in facilitating a student’s reflection on their own code.',
          ]}
        />
        <SubSection
          title={'What Will You Have to Do?'}
          body={[
            'The study will be conducted online and anonymously. You will be participating in this study by using this tool, which is of our own design. By clicking on the “Start” button, you are providing your consent for your data from this tool to be collected and studied. All data will be stored anonymously, so there will be no way to connect this data with you. If you are a student of the researchers, we give our assurance that your participation or non-participation in this study will have no effect on your grades or relationship with the University and that you may contact your academic head should you feel that this assurance has not been met.',
            'As part of this study, you are required to upload a file containing Python code that you have written and submitted as part of one of your recent coursework assignments to the tool we have developed. This study is completely unrelated to the assignment and nothing in this study will affect your mark for either the assignment that the code was originally submitted for, or for the course as a whole. You will be asked to answer five multiple choice questions that have been generated about your submitted code. After answering these questions, you will be directed to fill out a short questionnaire about your experiences using this tool.',
            'This is expected to take approximately 30 minutes.',
            'By participating in this study, you will help the researchers to understand the effectiveness of the tool and the questions that are being generated from the tool in facilitating reflection in learning.',
          ]}
        />
        <SubSection
          title={'Why Have You Been Invited to Take Part?'}
          body={[
            'You have been invited to take part in the study as a student studying in a first-year Computer Science course at the University of Auckland that involves programming in Python.',
          ]}
        />
      </AccordionDetails>
    </Accordion>
  )
}

interface SubSectionProps {
  title: string
  body: string[]
}

const SubSection = ({ title, body }: SubSectionProps) => {
  const renderBody = () => {
    return body.map((content) => <Typography>{content}</Typography>)
  }

  return (
    <Box
      sx={{
        // outline: '1px solid black',
        display: 'flex',
        flexDirection: 'column',
        rowGap: '.51rem',
      }}
    >
      <Typography variant="h5">{title}</Typography>
      {renderBody()}
    </Box>
  )
}

export default StudyOutline
